### ISSUE TITLE
Unable to load the extension on Chrome

### ISSUE THREAD

**Issue by ayushjain01** [PFython/pyscript-local-runtime#4]
I've been working on a project and came across your repository. I tried running it but encountered an error. Could you please assist me with this issue?

Here's the error I'm stuck at:

```
Uncaught (in promise) TypeError: Failed to resolve module specifier 'runtime/pyodide.js'
    at PyScriptApp._startInterpreter_main (pyscript.js:29022:7)
    at PyScriptApp.loadInterpreter (pyscript.js:29048:49)
    at PyScriptApp._realMain (pyscript.js:28972:18)
    at async PyScriptApp.main (pyscript.js:28940:9)
```

To provide more context, I've attached a screenshot of the error message:
![image](https://github.com/PFython/pyscript-local-runtime/assets/67141217/a4d7b4eb-83ce-45a8-83ec-34726b60954c)

I appreciate your help in resolving this issue. Thank you!

**Comment by PFython** [comment]
Sorry - PyScript continues to evolve and I don't have time to keep up or maintain this.  Very happy for other contributors to get involved though.

**Comment by rajatmohan22** [comment]
> I've been working on a project and came across your repository. I tried running it but encountered an error. Could you please assist me with this issue?
> 
> Here's the error I'm stuck at:
> 
> ```
> Uncaught (in promise) TypeError: Failed to resolve module specifier 'runtime/pyodide.js'
>     at PyScriptApp._startInterpreter_main (pyscript.js:29022:7)
>     at PyScriptApp.loadInterpreter (pyscript.js:29048:49)
>     at PyScriptApp._realMain (pyscript.js:28972:18)
>     at async PyScriptApp.main (pyscript.js:28940:9)
> ```
> 
> To provide more context, I've attached a screenshot of the error message: ![image](https://user-images.githubusercontent.com/67141217/252642357-a4d7b4eb-83ce-45a8-83ec-34726b60954c.png)
> 
> I appreciate your help in resolving this issue. Thank you!

The issue you are facing is simple. There is no runtime directory in the project. It has been renamed to interpreter. So cd into interpreter and then run the setup file. it should work.

**Comment by ayushjain01** [comment]
Hi @rajatmohan22,

Thanks for your response. I'm aware that the runtime directory was renamed in the latest commit. In fact, I was working with the specific commit [b68d9a1](https://github.com/PFython/pyscript-local-runtime/tree/b68d9a16ed86f54c54bf91b9bf9d21eb8903334c)

However, despite these changes, I'm still encountering the same error. I've attached a screenshot of the error for reference:

![Error Screenshot](https://github.com/PFython/pyscript-local-runtime/assets/67141217/e4913d5d-db41-4d86-9efb-897eb1711a80)

**Comment by SamuelPavlik** [comment]
There seems to be a problem with importing the `pyodide.js` file in the `_startInterpreter_main` function based on the given interpreter URL. One way to solve it is to change the failing line from `await import(interpreterURL);` to `await import('./pyodide.js');`. The problem seems to be specifically with the URL not starting with "./".
